### ISSUE TITLE
Feature Request - detach when shutting down

### ISSUE THREAD

**Issue by judo16** [irakhlin/hassio-usbip-mounter#6]
Hi there,

First of all, I'd likes to say thanks for creating this Home Assistant add-on. You don't know how useful it's been for instances with VMs, USB devices no where near the VM host, etc. The code you've done works great for me and is stable. I was wondering if it would be possible for it to run a detach command when HA is rebooting, shutting down and / or stopping the add-on so that the remote device is available to attach again once HA is up and running again?

Alternately, would it be possible to automate running commands remotely via SSH to unbind and bind the USB device uning the HA add-on when the add-on starts prior to attaching?

Thanks in advance :)

**Comment by irakhlin** [comment]
Sorry this took so long, this should now be working in version 1.4

**Comment by irakhlin** [comment]
resolved
