### ISSUE TITLE
Feature request: "-force" flag for client

### ISSUE THREAD

**Issue by acseven** [irakhlin/hassio-usbip-mounter#7]
Please allow a flag configuration for the "force" parameter; in my case I had to go into the docker addon bash session to get it to connect, by using the force flag.

**Comment by irakhlin** [comment]
Could you provide some additional information regarding where you are putting the '-force' flag? I am not positive if the usbip or usbipd daemon has a 'force' flag or what it would actually be doing?

**Comment by acseven** [comment]
Apologies, this was on the server side.
